#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    url: jdbc:h2:mem:db
#    password:
#  h2:
#    console:
#      enabled: 'true'
#      path: /h2-console
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    #defer-datasource-initialization: true
#    properties:
#      hibernate:
#        format_sql: 'true'
#        show_sql: 'true'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://localhost:5432/updates
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:      
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

## URL
host:
  webhost: https://api.msrc.microsoft.com/cvrf/v2.0/updates
