spring:
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: jdbc:postgresql://localhost:5432/updates
    username: postgres
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:      
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

## URL
host:
  webhost: https://api.msrc.microsoft.com/cvrf/v2.0/updates
